version: "3.9"

services:
  backend:
    build:
      context: ./tcg-backend
      dockerfile: Dockerfile
    container_name: tcgshop-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # IMPORTANTE: aqu√≠ luego cambiaremos <DB_PRIVATE_IP> por la IP privada real de la EC2 de DB
      SPRING_DATASOURCE_URL: "jdbc:mysql://172.31.24.157:3306/tcgshop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "tcguser"
      SPRING_DATASOURCE_PASSWORD: "TcgPass123!"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    volumes:
      # Carpeta local de uploads mapeada al contenedor
      - ./tcg-backend/uploads:/app/uploads
