version: "3.9"

services:
  frontend:
    build:
      context: ./FullstackII-FrontP2
      dockerfile: Dockerfile
    container_name: tcgshop-frontend
    restart: unless-stopped
    ports:
      - "80:80"
